version: '3.8'

networks:
  familytree.devnetwork:
    driver: bridge

services:
  familytree.api:
    depends_on:
      - "familytree.db"
    container_name: familytree_api
    build:
      context: ./src/api
      dockerfile: FamilyTree.App/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__FamilyTreeDatabase=User ID=postgres;Password=postgres;Server=familytree_db;Port=5432;Database=FamilyTreeDb;Pooling=true;
    ports:
      - "7006:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - familytree.devnetwork

  familytree.db:
    image: postgres:latest
    container_name: familytree_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FamilyTreeDb
    ports: 
      - "5433:5432"
    restart: always
    volumes: 
      - app_data:/var/lib/postgresql/data
    networks:
      - familytree.devnetwork
  
  familytree.webapp:
    depends_on:
      - "familytree.api"
    container_name: familytree_webapp
    build:
      context: ./src/webapp/family-tree
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    networks:
      - familytree.devnetwork
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://familytree.api:80

volumes:
  app_data:  