version: '3.8'

networks:
  familytree.devnetwork:
    driver: bridge

services:
  familytree.api:
    depends_on:
      - "familytree.db"
    container_name: familytree_api
    build:
      context: ./src
      dockerfile: FamilyTree.App/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__FamilyTreeDatabase=User ID=postgres;Password=postgres;Server=familytree_db;Port=5432;Database=FamilyTreeDb;IntegratedSecurity=true;Pooling=true;
      - RequiredHeaders__AllowedClientIds=["client-id-7c3de2b9-1b8a-423d-b18c-1817441823b8","client-id-3ff5d097-dd85-463a-bb52-5b51fe97fb51"]
    ports:
      - "7006:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - familytree.devnetwork

  familytree.db:
    image: postgres:latest
    container_name: familytree_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FamilyTreeDb
    ports: 
      - "5433:5432"
    restart: always
    volumes: 
      - app_data:/var/lib/postgresql/data
    networks:
      - familytree.devnetwork

volumes:
  app_data:  