// <auto-generated />
using System;
using FamilyTree.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyTree.Data.Migrations
{
    [DbContext(typeof(FamilyTreeDbContext))]
    partial class FamilyTreeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyTree.Application.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Famillies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a0a041f-dbf7-46bc-92e2-825d07d92d3c"),
                            Name = "Smith Family Tree"
                        },
                        new
                        {
                            Id = new Guid("a9f6214b-3f8e-4b4c-857b-5dba5d1a3f43"),
                            Name = "Johnson Family"
                        },
                        new
                        {
                            Id = new Guid("b1a8e62d-4499-4f34-8773-b9fa4e7d2c43"),
                            Name = "Smith Family"
                        },
                        new
                        {
                            Id = new Guid("f2a19d5c-3b4e-4d92-8827-6f5b2e34c812"),
                            Name = "Williams Family"
                        },
                        new
                        {
                            Id = new Guid("a5b8c72d-4f99-4e42-8913-6d7f31c8b2e1"),
                            Name = "Brown Family"
                        },
                        new
                        {
                            Id = new Guid("c1d9a72b-4f8c-4e92-8d7a-6b2f3e5c7a81"),
                            Name = "Gonzalez Family"
                        },
                        new
                        {
                            Id = new Guid("a3f7b92d-6c5e-4d12-8125-7b3a6f8d2e64"),
                            Name = "Baggins Family"
                        },
                        new
                        {
                            Id = new Guid("b3e7c92d-5f4c-4d12-8925-6b7f31a8d2e6"),
                            Name = "Potter Family"
                        },
                        new
                        {
                            Id = new Guid("c1a9d72b-4f8c-4e92-8d7a-6b2f3e5c7a81"),
                            Name = "Atreides Family"
                        });
                });

            modelBuilder.Entity("FamilyTree.Application.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BirthLocation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeathLocation")
                        .HasColumnType("text");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2a5bcfe-da88-46e7-8439-d8f5ec85c474"),
                            BirthDate = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "New York",
                            DeathLocation = "",
                            FamilyId = new Guid("0a0a041f-dbf7-46bc-92e2-825d07d92d3c"),
                            Gender = "Male",
                            GivenName = "John",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = new Guid("30e99d4d-4700-4c22-a1a3-ebdec1eb79b0"),
                            BirthLocation = "",
                            DeathDate = new DateTime(2015, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Los Angeles",
                            FamilyId = new Guid("0a0a041f-dbf7-46bc-92e2-825d07d92d3c"),
                            Gender = "Female",
                            GivenName = "Jane",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = new Guid("69d3685a-3b75-4c32-86a0-1dfbb585c10a"),
                            BirthDate = new DateTime(1910, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Chicago",
                            DeathLocation = "",
                            FamilyId = new Guid("0a0a041f-dbf7-46bc-92e2-825d07d92d3c"),
                            Gender = "Male",
                            GivenName = "Robert",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = new Guid("5eeceddf-f9a2-4b7e-b236-2dba0000cdbf"),
                            BirthDate = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Seattle",
                            DeathLocation = "",
                            FamilyId = new Guid("0a0a041f-dbf7-46bc-92e2-825d07d92d3c"),
                            Gender = "Female",
                            GivenName = "Emma",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("b7a63c14-9273-4cc5-ae35-ff8e8f43b8c2"),
                            BirthDate = new DateTime(1875, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Los Angeles",
                            FamilyId = new Guid("a9f6214b-3f8e-4b4c-857b-5dba5d1a3f43"),
                            Gender = "Male",
                            GivenName = "Robert",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("5e345c48-8a73-40cd-bff8-b92c8d3758c5"),
                            BirthDate = new DateTime(1977, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Los Angeles",
                            DeathDate = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Los Angeles",
                            FamilyId = new Guid("a9f6214b-3f8e-4b4c-857b-5dba5d1a3f43"),
                            Gender = "Female",
                            GivenName = "Linda",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("27c74ac5-ec57-4bc8-8fa9-6c1d82767f6d"),
                            BirthDate = new DateTime(2005, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Los Angeles",
                            FamilyId = new Guid("a9f6214b-3f8e-4b4c-857b-5dba5d1a3f43"),
                            Gender = "Female",
                            GivenName = "Sophia",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("8a97b09d-23c4-4fc8-8c02-d75284b2cf63"),
                            BirthDate = new DateTime(2008, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Los Angeles",
                            FamilyId = new Guid("a9f6214b-3f8e-4b4c-857b-5dba5d1a3f43"),
                            Gender = "Male",
                            GivenName = "Ethan",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("be42f68b-57f2-4721-8dc5-6d0c2fb2c8de"),
                            BirthDate = new DateTime(2011, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Los Angeles",
                            FamilyId = new Guid("a9f6214b-3f8e-4b4c-857b-5dba5d1a3f43"),
                            Gender = "Male",
                            GivenName = "Oliver",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("c4a76f38-5f77-499e-a1f1-65726b2e3f3d"),
                            BirthDate = new DateTime(1945, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "New York",
                            DeathDate = new DateTime(2020, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "New York",
                            FamilyId = new Guid("b1a8e62d-4499-4f34-8773-b9fa4e7d2c43"),
                            Gender = "Male",
                            GivenName = "Michael",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = new Guid("d3b57f28-3a88-4e02-bb36-2283f2b4d4a9"),
                            BirthDate = new DateTime(1948, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "New York",
                            DeathDate = new DateTime(2021, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "New York",
                            FamilyId = new Guid("b1a8e62d-4499-4f34-8773-b9fa4e7d2c43"),
                            Gender = "Female",
                            GivenName = "Sarah",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = new Guid("e5d79a14-92a7-4f92-81b2-6f3d38f66d99"),
                            BirthDate = new DateTime(1970, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "New York",
                            DeathDate = new DateTime(2018, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "New York",
                            FamilyId = new Guid("b1a8e62d-4499-4f34-8773-b9fa4e7d2c43"),
                            Gender = "Female",
                            GivenName = "Emily",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = new Guid("f872bfc3-99b7-4fd2-8715-3b6e2d42f887"),
                            BirthDate = new DateTime(1972, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "New York",
                            DeathDate = new DateTime(2015, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "New York",
                            FamilyId = new Guid("b1a8e62d-4499-4f34-8773-b9fa4e7d2c43"),
                            Gender = "Male",
                            GivenName = "Jack",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = new Guid("a9b63c14-9273-4cc5-ae35-ff8e8f43b8c2"),
                            BirthDate = new DateTime(2005, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "New York",
                            DeathDate = new DateTime(2022, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "New York",
                            FamilyId = new Guid("b1a8e62d-4499-4f34-8773-b9fa4e7d2c43"),
                            Gender = "Male",
                            GivenName = "Lucas",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = new Guid("b4c98e39-71d6-42d8-b185-3e3d21b5e5f2"),
                            BirthDate = new DateTime(2009, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "New York",
                            DeathDate = new DateTime(2023, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "New York",
                            FamilyId = new Guid("b1a8e62d-4499-4f34-8773-b9fa4e7d2c43"),
                            Gender = "Female",
                            GivenName = "Grace",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = new Guid("c6f87b24-51b7-4e72-91c2-4f3d38f66d22"),
                            BirthDate = new DateTime(2012, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "New York",
                            FamilyId = new Guid("b1a8e62d-4499-4f34-8773-b9fa4e7d2c43"),
                            Gender = "Male",
                            GivenName = "Ethan",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = new Guid("d972cfc3-71c7-4fd2-9925-5b6e2d42f777"),
                            BirthDate = new DateTime(2016, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "New York",
                            FamilyId = new Guid("b1a8e62d-4499-4f34-8773-b9fa4e7d2c43"),
                            Gender = "Female",
                            GivenName = "Madison",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = new Guid("a72b9f31-5c44-4f02-bd9a-3e7f2a6d1e59"),
                            BirthDate = new DateTime(1940, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Chicago",
                            DeathDate = new DateTime(2010, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Chicago",
                            FamilyId = new Guid("f2a19d5c-3b4e-4d92-8827-6f5b2e34c812"),
                            Gender = "Male",
                            GivenName = "Richard",
                            Surname = "Williams"
                        },
                        new
                        {
                            Id = new Guid("d4c79b12-8f25-4e91-9726-5f2d71a3b64e"),
                            BirthDate = new DateTime(1944, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Chicago",
                            DeathDate = new DateTime(2015, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Chicago",
                            FamilyId = new Guid("f2a19d5c-3b4e-4d92-8827-6f5b2e34c812"),
                            Gender = "Female",
                            GivenName = "Margaret",
                            Surname = "Williams"
                        },
                        new
                        {
                            Id = new Guid("f81a72c4-9e38-41b5-95d2-3c6d87f2b3e1"),
                            BirthDate = new DateTime(1968, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Chicago",
                            DeathDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Chicago",
                            FamilyId = new Guid("f2a19d5c-3b4e-4d92-8827-6f5b2e34c812"),
                            Gender = "Male",
                            GivenName = "David",
                            Surname = "Williams"
                        },
                        new
                        {
                            Id = new Guid("c9b6d4a1-52f3-4e92-b1c7-7e5f21d38a6b"),
                            BirthDate = new DateTime(1971, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Chicago",
                            DeathDate = new DateTime(2022, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Chicago",
                            FamilyId = new Guid("f2a19d5c-3b4e-4d92-8827-6f5b2e34c812"),
                            Gender = "Female",
                            GivenName = "Linda",
                            Surname = "Williams"
                        },
                        new
                        {
                            Id = new Guid("9a969a1e-a161-4727-9f4d-bc7a68fd6b87"),
                            BirthDate = new DateTime(1999, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Chicago",
                            DeathDate = new DateTime(2023, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Chicago",
                            FamilyId = new Guid("f2a19d5c-3b4e-4d92-8827-6f5b2e34c812"),
                            Gender = "Female",
                            GivenName = "Sophia",
                            Surname = "Williams"
                        },
                        new
                        {
                            Id = new Guid("b9d4e72a-5c6f-48f1-9123-7d38f21b5e74"),
                            BirthDate = new DateTime(2002, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Chicago",
                            FamilyId = new Guid("f2a19d5c-3b4e-4d92-8827-6f5b2e34c812"),
                            Gender = "Male",
                            GivenName = "Daniel",
                            Surname = "Williams"
                        },
                        new
                        {
                            Id = new Guid("c81b72d4-6e93-41f2-81d5-3f2a6c87b5e2"),
                            BirthDate = new DateTime(2007, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Chicago",
                            FamilyId = new Guid("f2a19d5c-3b4e-4d92-8827-6f5b2e34c812"),
                            Gender = "Female",
                            GivenName = "Olivia",
                            Surname = "Williams"
                        },
                        new
                        {
                            Id = new Guid("d97c6a2b-3e5f-4b91-9925-7f21d38a6b74"),
                            BirthDate = new DateTime(2011, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Chicago",
                            DeathDate = new DateTime(2022, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Chicago",
                            FamilyId = new Guid("f2a19d5c-3b4e-4d92-8827-6f5b2e34c812"),
                            Gender = "Male",
                            GivenName = "Henry",
                            Surname = "Williams"
                        },
                        new
                        {
                            Id = new Guid("e6a1c92d-5f3e-47d8-8123-6b7f21d3a5e4"),
                            BirthDate = new DateTime(2014, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Chicago",
                            FamilyId = new Guid("f2a19d5c-3b4e-4d92-8827-6f5b2e34c812"),
                            Gender = "Male",
                            GivenName = "Liam",
                            Surname = "Williams"
                        },
                        new
                        {
                            Id = new Guid("b7a4c89f-62d5-4e31-bd8a-2f3c7d1b96e4"),
                            BirthDate = new DateTime(1938, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Houston",
                            DeathDate = new DateTime(2005, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Houston",
                            FamilyId = new Guid("a5b8c72d-4f99-4e42-8913-6d7f31c8b2e1"),
                            Gender = "Male",
                            GivenName = "George",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = new Guid("c6f21d98-5b3e-471a-91d2-3f87c1b6d5e9"),
                            BirthDate = new DateTime(1942, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Houston",
                            DeathDate = new DateTime(2012, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Houston",
                            FamilyId = new Guid("a5b8c72d-4f99-4e42-8913-6d7f31c8b2e1"),
                            Gender = "Female",
                            GivenName = "Eleanor",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = new Guid("d97b3e5a-6c41-4f92-8125-7d2a6f8c5e74"),
                            BirthDate = new DateTime(1966, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Houston",
                            DeathDate = new DateTime(2020, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Houston",
                            FamilyId = new Guid("a5b8c72d-4f99-4e42-8913-6d7f31c8b2e1"),
                            Gender = "Male",
                            GivenName = "Jonathan",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = new Guid("e5a7b92d-6f3c-42d8-81a3-5b7d21c8f4e2"),
                            BirthDate = new DateTime(1969, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Houston",
                            DeathDate = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Houston",
                            FamilyId = new Guid("a5b8c72d-4f99-4e42-8913-6d7f31c8b2e1"),
                            Gender = "Female",
                            GivenName = "Catherine",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = new Guid("5ea9c874-0cf0-4bae-a7b1-7681036af33d"),
                            BirthDate = new DateTime(1995, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Houston",
                            DeathDate = new DateTime(2022, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Houston",
                            FamilyId = new Guid("a5b8c72d-4f99-4e42-8913-6d7f31c8b2e1"),
                            Gender = "Female",
                            GivenName = "Sophia",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = new Guid("af711e40-aaa7-43f1-a60c-fce2afe6adba"),
                            BirthDate = new DateTime(1998, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Houston",
                            FamilyId = new Guid("a5b8c72d-4f99-4e42-8913-6d7f31c8b2e1"),
                            Gender = "Male",
                            GivenName = "Noah",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = new Guid("b6e92a1d-5f3b-47d8-91c2-3f7d2a6b5e14"),
                            BirthDate = new DateTime(2003, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Houston",
                            FamilyId = new Guid("a5b8c72d-4f99-4e42-8913-6d7f31c8b2e1"),
                            Gender = "Female",
                            GivenName = "Emma",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = new Guid("c97b2e5a-3f6d-4b91-9925-5a7d2a6f8c74"),
                            BirthDate = new DateTime(2007, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Houston",
                            FamilyId = new Guid("a5b8c72d-4f99-4e42-8913-6d7f31c8b2e1"),
                            Gender = "Male",
                            GivenName = "Lucas",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = new Guid("d8a6b3e7-5c92-47d8-8123-6b2f7d1a5e34"),
                            BirthDate = new DateTime(2012, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Houston",
                            FamilyId = new Guid("a5b8c72d-4f99-4e42-8913-6d7f31c8b2e1"),
                            Gender = "Female",
                            GivenName = "Madison",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = new Guid("e5b71d92-6f3c-42d8-81a3-7d2f6b3e5a24"),
                            BirthDate = new DateTime(2016, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Houston",
                            FamilyId = new Guid("a5b8c72d-4f99-4e42-8913-6d7f31c8b2e1"),
                            Gender = "Male",
                            GivenName = "Henry",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = new Guid("d5b72c3a-9f41-4e92-8125-6b7f2a1d8e34"),
                            BirthDate = new DateTime(1950, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Mexico City",
                            DeathDate = new DateTime(2018, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Mexico City",
                            FamilyId = new Guid("c1d9a72b-4f8c-4e92-8d7a-6b2f3e5c7a81"),
                            Gender = "Male",
                            GivenName = "Carlos",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            Id = new Guid("e6a1d92b-5f3c-47d8-91a2-3b7d2a6f8e24"),
                            BirthDate = new DateTime(1955, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Mexico City",
                            DeathDate = new DateTime(2022, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Mexico City",
                            FamilyId = new Guid("c1d9a72b-4f8c-4e92-8d7a-6b2f3e5c7a81"),
                            Gender = "Female",
                            GivenName = "Isabella",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            Id = new Guid("f87c2b6a-3f5d-4e92-9925-5a7d1a6b2e74"),
                            BirthDate = new DateTime(1982, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Mexico City",
                            FamilyId = new Guid("c1d9a72b-4f8c-4e92-8d7a-6b2f3e5c7a81"),
                            Gender = "Male",
                            GivenName = "Ricardo",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            Id = new Guid("a9d72b5a-6f3c-42d8-81a3-7b2f6d3e5a24"),
                            BirthDate = new DateTime(1985, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Mexico City",
                            FamilyId = new Guid("c1d9a72b-4f8c-4e92-8d7a-6b2f3e5c7a81"),
                            Gender = "Female",
                            GivenName = "Sofia",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            Id = new Guid("b6e92a1d-5f3b-47d8-81c2-3f7d2a6b5e14"),
                            BirthDate = new DateTime(2015, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Mexico City",
                            FamilyId = new Guid("c1d9a72b-4f8c-4e92-8d7a-6b2f3e5c7a81"),
                            Gender = "Male",
                            GivenName = "Mateo",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            Id = new Guid("7b72b5f1-3010-4a68-8cc5-815b6cc4e4fb"),
                            BirthDate = new DateTime(1920, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "London",
                            DeathDate = new DateTime(2001, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "London",
                            FamilyId = new Guid("a3f7b92d-6c5e-4d12-8125-7b3a6f8d2e64"),
                            Gender = "Male",
                            GivenName = "Bilbo",
                            Surname = "Baggins"
                        },
                        new
                        {
                            Id = new Guid("8c708c1f-4e48-486b-933f-6b8aff07266f"),
                            BirthDate = new DateTime(1925, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "London",
                            DeathDate = new DateTime(1994, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "London",
                            FamilyId = new Guid("a3f7b92d-6c5e-4d12-8125-7b3a6f8d2e64"),
                            Gender = "Female",
                            GivenName = "Belladonna",
                            Surname = "Baggins"
                        },
                        new
                        {
                            Id = new Guid("6f8dcc83-05a0-433f-82f6-f4006a9abf19"),
                            BirthDate = new DateTime(1968, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "London",
                            DeathDate = new DateTime(2020, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "London",
                            FamilyId = new Guid("a3f7b92d-6c5e-4d12-8125-7b3a6f8d2e64"),
                            Gender = "Male",
                            GivenName = "Frodo",
                            Surname = "Baggins"
                        },
                        new
                        {
                            Id = new Guid("faa7efa2-75f6-4457-a397-209b047ccdee"),
                            BirthDate = new DateTime(1950, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "London",
                            DeathDate = new DateTime(1999, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "London",
                            FamilyId = new Guid("a3f7b92d-6c5e-4d12-8125-7b3a6f8d2e64"),
                            Gender = "Male",
                            GivenName = "Drogo",
                            Surname = "Baggins"
                        },
                        new
                        {
                            Id = new Guid("8bb30818-22c7-434b-a159-80c5040ee3c0"),
                            BirthDate = new DateTime(1952, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "London",
                            DeathDate = new DateTime(1999, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "London",
                            FamilyId = new Guid("a3f7b92d-6c5e-4d12-8125-7b3a6f8d2e64"),
                            Gender = "Female",
                            GivenName = "Primula",
                            Surname = "Baggins"
                        },
                        new
                        {
                            Id = new Guid("a9d41c72-6b5e-49f2-8123-7d3a6f8b2e64"),
                            BirthDate = new DateTime(1975, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "London",
                            FamilyId = new Guid("a3f7b92d-6c5e-4d12-8125-7b3a6f8d2e64"),
                            Gender = "Male",
                            GivenName = "Samwise",
                            Surname = "Baggins"
                        },
                        new
                        {
                            Id = new Guid("86dc9f24-2885-4d73-a02f-ce247805f3fc"),
                            BirthDate = new DateTime(1880, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "London",
                            DeathDate = new DateTime(1940, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "London",
                            FamilyId = new Guid("b3e7c92d-5f4c-4d12-8925-6b7f31a8d2e6"),
                            Gender = "Male",
                            GivenName = "Henry",
                            Surname = "Potter"
                        },
                        new
                        {
                            Id = new Guid("f23f864a-b937-4ab3-ac4c-a08c841cdcbf"),
                            BirthDate = new DateTime(1910, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "London",
                            DeathDate = new DateTime(1970, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "London",
                            FamilyId = new Guid("b3e7c92d-5f4c-4d12-8925-6b7f31a8d2e6"),
                            Gender = "Male",
                            GivenName = "Charlus",
                            Surname = "Potter"
                        },
                        new
                        {
                            Id = new Guid("e5a72c9b-6f3d-47d2-8325-4f91b72d3e86"),
                            BirthDate = new DateTime(1912, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "London",
                            DeathDate = new DateTime(1977, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "London",
                            FamilyId = new Guid("b3e7c92d-5f4c-4d12-8925-6b7f31a8d2e6"),
                            Gender = "Female",
                            GivenName = "Dorea",
                            Surname = "Black Potter"
                        },
                        new
                        {
                            Id = new Guid("f8b72c3d-91d5-4e42-8326-5f2a6b7d3e14"),
                            BirthDate = new DateTime(1960, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "London",
                            DeathDate = new DateTime(1981, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Godric's Hollow",
                            FamilyId = new Guid("b3e7c92d-5f4c-4d12-8925-6b7f31a8d2e6"),
                            Gender = "Male",
                            GivenName = "James",
                            Surname = "Potter"
                        },
                        new
                        {
                            Id = new Guid("023ff397-e06c-42a9-8170-b872c834315b"),
                            BirthDate = new DateTime(1960, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Cokeworth",
                            DeathDate = new DateTime(1981, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Godric's Hollow",
                            FamilyId = new Guid("b3e7c92d-5f4c-4d12-8925-6b7f31a8d2e6"),
                            Gender = "Female",
                            GivenName = "Lily",
                            Surname = "Evans Potter"
                        },
                        new
                        {
                            Id = new Guid("e3badc5d-a88f-4b6b-aaed-1cc764c0a2b8"),
                            BirthDate = new DateTime(1980, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Godric's Hollow",
                            FamilyId = new Guid("b3e7c92d-5f4c-4d12-8925-6b7f31a8d2e6"),
                            Gender = "Male",
                            GivenName = "Harry",
                            Surname = "Potter"
                        },
                        new
                        {
                            Id = new Guid("c6a1d92b-5f3c-42d8-81a2-3b7d2a6f8e26"),
                            BirthDate = new DateTime(1981, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Ottery St Catchpole",
                            FamilyId = new Guid("b3e7c92d-5f4c-4d12-8925-6b7f31a8d2e6"),
                            Gender = "Female",
                            GivenName = "Ginny",
                            Surname = "Weasley Potter"
                        },
                        new
                        {
                            Id = new Guid("b7c92a5d-3f6e-41d8-99a5-5f7d2a6b3e24"),
                            BirthDate = new DateTime(1875, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Athens",
                            DeathDate = new DateTime(1945, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Athens",
                            FamilyId = new Guid("c1a9d72b-4f8c-4e92-8d7a-6b2f3e5c7a81"),
                            Gender = "Male",
                            GivenName = "Victor",
                            Surname = "Atreides"
                        },
                        new
                        {
                            Id = new Guid("c6a1d92b-5f3c-42d8-81a2-3b7d2a6f8e24"),
                            BirthDate = new DateTime(1880, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Athens",
                            DeathDate = new DateTime(1950, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Athens",
                            FamilyId = new Guid("c1a9d72b-4f8c-4e92-8d7a-6b2f3e5c7a81"),
                            Gender = "Female",
                            GivenName = "Helena",
                            Surname = "Atreides"
                        },
                        new
                        {
                            Id = new Guid("d8b72c3a-9f41-4e92-8125-6b7f2a1d8e34"),
                            BirthDate = new DateTime(1935, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Athens",
                            DeathDate = new DateTime(1980, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Lisbon",
                            FamilyId = new Guid("c1a9d72b-4f8c-4e92-8d7a-6b2f3e5c7a81"),
                            Gender = "Male",
                            GivenName = "Leto",
                            Surname = "Atreides"
                        },
                        new
                        {
                            Id = new Guid("d9168577-b6ed-4e3a-9bae-8d805be65d18"),
                            BirthDate = new DateTime(1940, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Lisbon",
                            DeathDate = new DateTime(2010, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathLocation = "Lisbon",
                            FamilyId = new Guid("c1a9d72b-4f8c-4e92-8d7a-6b2f3e5c7a81"),
                            Gender = "Female",
                            GivenName = "Jessica",
                            Surname = "Atreides"
                        },
                        new
                        {
                            Id = new Guid("26218dc0-0a44-4b8b-8361-332b3b1c22e9"),
                            BirthDate = new DateTime(1965, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Lisbon",
                            FamilyId = new Guid("c1a9d72b-4f8c-4e92-8d7a-6b2f3e5c7a81"),
                            Gender = "Male",
                            GivenName = "Paul",
                            Surname = "Atreides"
                        },
                        new
                        {
                            Id = new Guid("10c9e73f-8bf1-47cf-8e4a-62781780c519"),
                            BirthDate = new DateTime(1970, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthLocation = "Lisbon",
                            FamilyId = new Guid("c1a9d72b-4f8c-4e92-8d7a-6b2f3e5c7a81"),
                            Gender = "Female",
                            GivenName = "Alia",
                            Surname = "Atreides"
                        });
                });

            modelBuilder.Entity("FamilyTree.Application.Entities.Person", b =>
                {
                    b.HasOne("FamilyTree.Application.Entities.Family", null)
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyTree.Application.Entities.Family", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
